security:
    basic:
        enabled: false
management:
    security:
        enabled: false

greeting:
    displayFortune: true
    
quoteServiceURL: http://quote-service-dev.cfapps.io/quote